-- The Shift: apply migration 0009 (the Debrief record and the Work Plan fields).
-- Does exactly what `pnpm db:migrate` would: creates the debriefs table, adds weekNumber and sortOrder to
-- engagement_sessions and engagement_tasks, adds factor to engagement_tasks, and records the migration in
-- drizzle.__drizzle_migrations, so `pnpm db:verify` and later migrations stay in step. Additive only: no existing
-- column changes, no data touched. Safe to run once: it stops, changing nothing, unless the database is exactly at
-- migration 0008. Paste the whole script into the Supabase SQL Editor and press Run. Generated from
-- drizzle/migrations/0009_debrief_work_plan.sql; regenerate it if that file changes.

begin;

do $guard$
declare
  applied integer;
begin
  select count(*) into applied from drizzle.__drizzle_migrations;
  if applied <> 9 then
    raise exception 'Stopped, nothing changed: expected 9 recorded migrations (0000 to 0008), found %.', applied;
  end if;
  if not exists (select 1 from drizzle.__drizzle_migrations where hash = 'ae477235dbb88933681b7189e121800b4b7fc30ed218660d2b8855c72719d0eb') then
    raise exception 'Stopped, nothing changed: migration 0008 is not recorded.';
  end if;
  if to_regclass('public.debriefs') is not null then
    raise exception 'Stopped, nothing changed: the debriefs table already exists.';
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'engagement_tasks' and column_name = 'weekNumber') then
    raise exception 'Stopped, nothing changed: engagement_tasks already has weekNumber.';
  end if;
end
$guard$;

-- 0009_debrief_work_plan
CREATE TYPE "public"."engagement_tasks_factor" AS ENUM('internal', 'external');
CREATE TABLE "debriefs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "debriefs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessCheckId" integer NOT NULL,
	"heldAt" timestamp with time zone,
	"heard" text,
	"problemInOwnerWords" text,
	"successLooksLike" text,
	"tried" text,
	"nextSteps" text,
	"capturedByUserId" integer,
	"sharedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "debriefs_businessCheckId_unique" UNIQUE("businessCheckId")
);
ALTER TABLE "engagement_sessions" ADD COLUMN "weekNumber" integer;
ALTER TABLE "engagement_sessions" ADD COLUMN "sortOrder" integer DEFAULT 0 NOT NULL;
ALTER TABLE "engagement_tasks" ADD COLUMN "weekNumber" integer;
ALTER TABLE "engagement_tasks" ADD COLUMN "sortOrder" integer DEFAULT 0 NOT NULL;
ALTER TABLE "engagement_tasks" ADD COLUMN "factor" "engagement_tasks_factor";
ALTER TABLE "debriefs" ADD CONSTRAINT "debriefs_businessCheckId_business_checks_id_fk" FOREIGN KEY ("businessCheckId") REFERENCES "public"."business_checks"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "debriefs" ADD CONSTRAINT "debriefs_capturedByUserId_users_id_fk" FOREIGN KEY ("capturedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

-- Record it, exactly as drizzle-kit does (hash of the file, timestamp from the journal).
insert into drizzle.__drizzle_migrations (hash, created_at) values ('56a431e9b4fcd03732b0ffef16117a41d4e8bc4c6f04429857a71af64a59a781', 1791622182142);

commit;

-- Check: should say 1 debriefs table, 3 new task columns and 10 recorded migrations.
select (select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'debriefs') as debriefs_table,
       (select count(*) from information_schema.columns where table_schema = 'public' and table_name = 'engagement_tasks' and column_name in ('weekNumber', 'sortOrder', 'factor')) as task_columns,
       (select count(*) from drizzle.__drizzle_migrations) as recorded_migrations;
