CREATE TYPE "public"."account_invitations_delivery_status" AS ENUM('Sent', 'Failed', 'Simulated');--> statement-breakpoint
CREATE TYPE "public"."account_invitations_kind" AS ENUM('staff', 'business_member');--> statement-breakpoint
CREATE TYPE "public"."account_invitations_status" AS ENUM('pending', 'accepted', 'revoked', 'expired');--> statement-breakpoint
CREATE TYPE "public"."client_access_level" AS ENUM('full', 'contributor');--> statement-breakpoint
CREATE TYPE "public"."engagement_audience" AS ENUM('team', 'owner', 'business');--> statement-breakpoint
CREATE TYPE "public"."engagement_deliverables_kind" AS ENUM('findings', 'problem_statement', 'prescription', 'tools', 'plan', 'other');--> statement-breakpoint
CREATE TYPE "public"."engagement_deliverables_status" AS ENUM('draft', 'awaiting_approval', 'approved', 'shared');--> statement-breakpoint
CREATE TYPE "public"."engagement_sessions_kind" AS ENUM('assessment_call', 'check_in', 'review', 'other');--> statement-breakpoint
CREATE TYPE "public"."engagement_sessions_status" AS ENUM('planned', 'held', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."engagement_tasks_kind" AS ENUM('data_request', 'action');--> statement-breakpoint
CREATE TYPE "public"."engagement_tasks_side" AS ENUM('client', 'ipf');--> statement-breakpoint
CREATE TYPE "public"."engagement_tasks_status" AS ENUM('open', 'received', 'accepted', 'needs_more', 'done', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."engagement_team_role" AS ENUM('lead', 'analyst', 'partner', 'expert');--> statement-breakpoint
CREATE TYPE "public"."engagements_stage" AS ENUM('setting_up', 'assessment', 'fix', 'plan', 'closed');--> statement-breakpoint
CREATE TABLE "account_invitations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_invitations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" "account_invitations_kind" NOT NULL,
	"email" varchar(320) NOT NULL,
	"fullName" varchar(255) NOT NULL,
	"platformRole" "user_platform_roles_role",
	"businessId" integer,
	"access" "client_access_level",
	"tokenHash" varchar(64) NOT NULL,
	"status" "account_invitations_status" DEFAULT 'pending' NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"createdByUserId" integer NOT NULL,
	"acceptedByUserId" integer,
	"acceptedAt" timestamp with time zone,
	"revokedAt" timestamp with time zone,
	"deliveryStatus" "account_invitations_delivery_status" DEFAULT 'Simulated' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_invitations_tokenHash_unique" UNIQUE("tokenHash")
);
--> statement-breakpoint
CREATE TABLE "business_member_access" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "business_member_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"membershipId" integer NOT NULL,
	"access" "client_access_level" NOT NULL,
	"grantedByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "business_member_access_membershipId_unique" UNIQUE("membershipId")
);
--> statement-breakpoint
CREATE TABLE "engagement_checkins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_checkins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"weekNumber" integer NOT NULL,
	"heldOn" date,
	"progress" text,
	"blockers" text,
	"nextStep" text,
	"measureReading" numeric(18, 4),
	"questionsAsked" text,
	"hoursLead" numeric(5, 2),
	"hoursAnalyst" numeric(5, 2),
	"hoursPartner" numeric(5, 2),
	"aiUsed" boolean,
	"recordedByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "engagement_checkins_engagement_week_unique" UNIQUE("engagementId","weekNumber")
);
--> statement-breakpoint
CREATE TABLE "engagement_comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"deliverableId" integer NOT NULL,
	"authorUserId" integer NOT NULL,
	"body" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "engagement_deliverables" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_deliverables_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"kind" "engagement_deliverables_kind" NOT NULL,
	"title" varchar(200) NOT NULL,
	"summary" text,
	"status" "engagement_deliverables_status" DEFAULT 'draft' NOT NULL,
	"audience" "engagement_audience" DEFAULT 'owner' NOT NULL,
	"approvedByUserId" integer,
	"approvedAt" timestamp with time zone,
	"sharedByUserId" integer,
	"sharedAt" timestamp with time zone,
	"clientAcceptedByUserId" integer,
	"clientAcceptedAt" timestamp with time zone,
	"createdByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "engagement_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"taskId" integer,
	"deliverableId" integer,
	"storageKey" varchar(512) NOT NULL,
	"fileName" varchar(255) NOT NULL,
	"contentType" varchar(128) NOT NULL,
	"sizeBytes" integer NOT NULL,
	"audience" "engagement_audience" DEFAULT 'owner' NOT NULL,
	"uploadedByUserId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "engagement_files_storageKey_unique" UNIQUE("storageKey")
);
--> statement-breakpoint
CREATE TABLE "engagement_measures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_measures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"name" varchar(160) NOT NULL,
	"definition" text,
	"unit" varchar(32),
	"baselineValue" numeric(18, 4),
	"targetValue" numeric(18, 4),
	"createdByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "engagement_measures_engagementId_unique" UNIQUE("engagementId")
);
--> statement-breakpoint
CREATE TABLE "engagement_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"kind" "engagement_sessions_kind" NOT NULL,
	"title" varchar(160) NOT NULL,
	"scheduledFor" timestamp with time zone,
	"durationMinutes" integer,
	"meetingLink" varchar(512),
	"agenda" text,
	"status" "engagement_sessions_status" DEFAULT 'planned' NOT NULL,
	"clientNotes" text,
	"internalNotes" text,
	"notesAudience" "engagement_audience" DEFAULT 'owner' NOT NULL,
	"notesSharedAt" timestamp with time zone,
	"notesSharedByUserId" integer,
	"createdByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "engagement_tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"kind" "engagement_tasks_kind" NOT NULL,
	"title" varchar(200) NOT NULL,
	"detail" text,
	"side" "engagement_tasks_side" NOT NULL,
	"assigneeUserId" integer,
	"dueOn" date,
	"status" "engagement_tasks_status" DEFAULT 'open' NOT NULL,
	"statusNote" varchar(500),
	"sessionId" integer,
	"createdByUserId" integer,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "engagement_team" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagement_team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"engagementId" integer NOT NULL,
	"userId" integer NOT NULL,
	"role" "engagement_team_role" NOT NULL,
	"assignedByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "engagement_team_engagement_user_unique" UNIQUE("engagementId","userId")
);
--> statement-breakpoint
CREATE TABLE "engagements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "engagements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessCheckId" integer NOT NULL,
	"businessId" integer,
	"paymentRequestId" integer,
	"stage" "engagements_stage" DEFAULT 'setting_up' NOT NULL,
	"problemArea" integer,
	"subProblem" varchar(255),
	"problemStatement" text,
	"assessmentStartedAt" timestamp with time zone,
	"fixStartedAt" timestamp with time zone,
	"closedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "engagements_businessCheckId_unique" UNIQUE("businessCheckId")
);
--> statement-breakpoint
ALTER TABLE "account_invitations" ADD CONSTRAINT "account_invitations_businessId_businesses_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."businesses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_invitations" ADD CONSTRAINT "account_invitations_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_invitations" ADD CONSTRAINT "account_invitations_acceptedByUserId_users_id_fk" FOREIGN KEY ("acceptedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "business_member_access" ADD CONSTRAINT "business_member_access_membershipId_business_memberships_id_fk" FOREIGN KEY ("membershipId") REFERENCES "public"."business_memberships"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "business_member_access" ADD CONSTRAINT "business_member_access_grantedByUserId_users_id_fk" FOREIGN KEY ("grantedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_checkins" ADD CONSTRAINT "engagement_checkins_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_checkins" ADD CONSTRAINT "engagement_checkins_recordedByUserId_users_id_fk" FOREIGN KEY ("recordedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_comments" ADD CONSTRAINT "engagement_comments_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_comments" ADD CONSTRAINT "engagement_comments_deliverableId_engagement_deliverables_id_fk" FOREIGN KEY ("deliverableId") REFERENCES "public"."engagement_deliverables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_comments" ADD CONSTRAINT "engagement_comments_authorUserId_users_id_fk" FOREIGN KEY ("authorUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_deliverables" ADD CONSTRAINT "engagement_deliverables_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_deliverables" ADD CONSTRAINT "engagement_deliverables_approvedByUserId_users_id_fk" FOREIGN KEY ("approvedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_deliverables" ADD CONSTRAINT "engagement_deliverables_sharedByUserId_users_id_fk" FOREIGN KEY ("sharedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_deliverables" ADD CONSTRAINT "engagement_deliverables_clientAcceptedByUserId_users_id_fk" FOREIGN KEY ("clientAcceptedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_deliverables" ADD CONSTRAINT "engagement_deliverables_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_files" ADD CONSTRAINT "engagement_files_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_files" ADD CONSTRAINT "engagement_files_taskId_engagement_tasks_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."engagement_tasks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_files" ADD CONSTRAINT "engagement_files_deliverableId_engagement_deliverables_id_fk" FOREIGN KEY ("deliverableId") REFERENCES "public"."engagement_deliverables"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_files" ADD CONSTRAINT "engagement_files_uploadedByUserId_users_id_fk" FOREIGN KEY ("uploadedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_measures" ADD CONSTRAINT "engagement_measures_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_measures" ADD CONSTRAINT "engagement_measures_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_sessions" ADD CONSTRAINT "engagement_sessions_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_sessions" ADD CONSTRAINT "engagement_sessions_notesSharedByUserId_users_id_fk" FOREIGN KEY ("notesSharedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_sessions" ADD CONSTRAINT "engagement_sessions_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD CONSTRAINT "engagement_tasks_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD CONSTRAINT "engagement_tasks_assigneeUserId_users_id_fk" FOREIGN KEY ("assigneeUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD CONSTRAINT "engagement_tasks_sessionId_engagement_sessions_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."engagement_sessions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD CONSTRAINT "engagement_tasks_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_team" ADD CONSTRAINT "engagement_team_engagementId_engagements_id_fk" FOREIGN KEY ("engagementId") REFERENCES "public"."engagements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_team" ADD CONSTRAINT "engagement_team_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagement_team" ADD CONSTRAINT "engagement_team_assignedByUserId_users_id_fk" FOREIGN KEY ("assignedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagements" ADD CONSTRAINT "engagements_businessCheckId_business_checks_id_fk" FOREIGN KEY ("businessCheckId") REFERENCES "public"."business_checks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagements" ADD CONSTRAINT "engagements_businessId_businesses_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."businesses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "engagements" ADD CONSTRAINT "engagements_paymentRequestId_payment_requests_id_fk" FOREIGN KEY ("paymentRequestId") REFERENCES "public"."payment_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "account_invitations_one_pending_per_email" ON "account_invitations" USING btree (lower("email")) WHERE "account_invitations"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "engagement_comments_deliverable_idx" ON "engagement_comments" USING btree ("deliverableId");--> statement-breakpoint
CREATE INDEX "engagement_deliverables_engagement_idx" ON "engagement_deliverables" USING btree ("engagementId");--> statement-breakpoint
CREATE INDEX "engagement_files_engagement_idx" ON "engagement_files" USING btree ("engagementId");--> statement-breakpoint
CREATE INDEX "engagement_sessions_engagement_idx" ON "engagement_sessions" USING btree ("engagementId");--> statement-breakpoint
CREATE INDEX "engagement_tasks_engagement_idx" ON "engagement_tasks" USING btree ("engagementId");--> statement-breakpoint
CREATE INDEX "engagement_team_user_idx" ON "engagement_team" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "engagements_business_idx" ON "engagements" USING btree ("businessId");--> statement-breakpoint
CREATE INDEX "engagements_stage_idx" ON "engagements" USING btree ("stage");