CREATE TYPE "public"."engagement_tasks_factor" AS ENUM('internal', 'external');--> statement-breakpoint
CREATE TABLE "debriefs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "debriefs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessCheckId" integer NOT NULL,
	"heldAt" timestamp with time zone,
	"heard" text,
	"problemInOwnerWords" text,
	"successLooksLike" text,
	"tried" text,
	"nextSteps" text,
	"capturedByUserId" integer,
	"sharedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "debriefs_businessCheckId_unique" UNIQUE("businessCheckId")
);
--> statement-breakpoint
ALTER TABLE "engagement_sessions" ADD COLUMN "weekNumber" integer;--> statement-breakpoint
ALTER TABLE "engagement_sessions" ADD COLUMN "sortOrder" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD COLUMN "weekNumber" integer;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD COLUMN "sortOrder" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "engagement_tasks" ADD COLUMN "factor" "engagement_tasks_factor";--> statement-breakpoint
ALTER TABLE "debriefs" ADD CONSTRAINT "debriefs_businessCheckId_business_checks_id_fk" FOREIGN KEY ("businessCheckId") REFERENCES "public"."business_checks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debriefs" ADD CONSTRAINT "debriefs_capturedByUserId_users_id_fk" FOREIGN KEY ("capturedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;